# Travis CI Java documentation can be found in:
# https://docs.travis-ci.com/user/languages/java/

# This enables the 'defaults' to test java applications:
language: android
jdk: openjdk10
sudo: false

android:
  components: # Cookbooks version: https://github.com/travis-ci/travis-cookbooks/tree/9c6cd11
    - armeabi-v7a-android-24
    - build-tools-29.0.2 # Match build-tools version used in build.gradle
    - android-29

before_script:
  - echo no | android create avd --force -n test -t android-29 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
 
script: ./gradlew build connectedCheck
  
# lintOptions:{
  #abortOnError false
#}

# Each job in Travis CI has several steps:
# https://docs.travis-ci.com/user/job-lifecycle/
# The 'language: java' directive sets up sane defaults to test common java applications
# We use the defaults for installing dependencies, compiling and testing maven applications
# In our case it will be 'mvn install' followed by 'mvn test'

# This is to enable CodeCov's coverage
# If a build is successful, the code is submitted for coverage analysis
after_success:
  - bash <(curl -s https://codecov.io/bash)
licenses:
  - yes | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-29"
  - yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;29.0.2"
